### ISSUE TITLE
Issue with segmentation in the sel_map

### ISSUE THREAD

**Issue by enginksz** [roahmlab/sel_map#8]
Hello,

First and foremost, thank you for sharing your work. After completing the relevant installations, I followed the steps below in the terminal and obtained the output:
![seg_ros](https://github.com/roahmlab/sel_map/assets/38870269/8b846db4-572c-4241-a979-786756fd0d76)

As you can see in the image, there is no segmentation and mapping. 
I don't get any error in terminal either. How we can solve this problem ?

Thanks,

**Comment by BuildingAtom** [comment]
Hi enginksz,

If you're using one of our prerecorded data bags, can you make sure that you're using the right launchfile (this hasn't been updated in the readme) `spot_bag_sel.launch` and using `--clock` with rosbag? And to remove the possibility of the GPU being the issue, can you try launching with `semseg_config:=Bypass.yaml`?

Otherwise, do you mind sharing some more information about your setup along with logs? You can get the logfile location for all roslaunches in a given roscore run by running `roslaunch-logs`. 

Adam

**Comment by enginksz** [comment]
Hi Adam, It worked with spot_bag_sel.launch :) 

Thanks
